# Generated by Django 2.0.5 on 2019-07-09 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='', help_text='项目名称', max_length=50, verbose_name='项目名称')),
                ('project_status', models.CharField(blank=True, choices=[('S0', '未开始'), ('S1', '进行中'), ('S3', '已结束'), ('S4', '阻塞停止')], default='S0', max_length=10, null=True, verbose_name='项目状态')),
                ('project_start_time', models.DateTimeField(blank=True, default='', null=True, verbose_name='项目开始时间')),
                ('project_end_time', models.DateTimeField(blank=True, default='', null=True, verbose_name='项目结束时间')),
                ('project_user_time', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='项目历时（以天为单位）')),
                ('requirement_status', models.CharField(blank=True, choices=[('S0', '未开始收集'), ('S1', '收集进行中'), ('S3', '收集已完毕'), ('S4', '无需求')], default='S0', max_length=10, null=True, verbose_name='需求状态')),
                ('requirement_start_time', models.DateTimeField(blank=True, default='', null=True, verbose_name='需求收集开始时间')),
                ('requirement_end_time', models.DateTimeField(blank=True, default='', null=True, verbose_name='需求收集结束时间')),
                ('requirement_user_time', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='需求收集历时（以天为单位）')),
                ('develop_status', models.CharField(blank=True, choices=[('S0', '未开始开发'), ('S1', '开发进行中'), ('S3', '开发已完毕'), ('S4', '不开发')], default='S0', max_length=10, null=True, verbose_name='开发状态')),
                ('develop_start_time', models.DateTimeField(blank=True, default='', null=True, verbose_name='开发开始时间')),
                ('develop_end_time', models.DateTimeField(blank=True, default='', null=True, verbose_name='开发结束时间')),
                ('develop_user_time', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='开发历时（以天为单位）')),
                ('test_status', models.CharField(blank=True, choices=[('S0', '未开始测试'), ('S1', '测试进行中'), ('S3', '测试已完毕'), ('S4', '不测试')], default='S0', max_length=10, null=True, verbose_name='测试状态')),
                ('test_start_time', models.DateTimeField(blank=True, default='', null=True, verbose_name='测试开始时间')),
                ('test_end_time', models.DateTimeField(blank=True, default='', null=True, verbose_name='测试结束时间')),
                ('test_user_time', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='测试历时（以天为单位）')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('develop_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='developleader', to=settings.AUTH_USER_MODEL, verbose_name='开发总监')),
                ('develop_staff', models.ManyToManyField(blank=True, null=True, related_name='developstaff', to=settings.AUTH_USER_MODEL, verbose_name='开发人员')),
                ('product_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='productleader', to=settings.AUTH_USER_MODEL, verbose_name='产品总监')),
                ('product_staff', models.ManyToManyField(blank=True, null=True, related_name='productstaff', to=settings.AUTH_USER_MODEL, verbose_name='产品人员')),
                ('project_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projectleader', to=settings.AUTH_USER_MODEL, verbose_name='项目总监')),
                ('test_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='testleader', to=settings.AUTH_USER_MODEL, verbose_name='测试总监')),
                ('test_staff', models.ManyToManyField(blank=True, null=True, related_name='teststaff', to=settings.AUTH_USER_MODEL, verbose_name='测试人员')),
            ],
            options={
                'verbose_name': '项目进度统计',
                'verbose_name_plural': '项目进度统计',
            },
        ),
    ]
