# Generated by Django 2.0.5 on 2019-01-14 18:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_project', models.CharField(default='', max_length=50, verbose_name='测试项目')),
                ('test_module', models.CharField(default='', max_length=50, verbose_name='测试模块')),
                ('test_page', models.CharField(default='', max_length=50, verbose_name='测试页面')),
                ('requirement_function', models.TextField(default='', verbose_name='功能点')),
                ('case_priority', models.CharField(blank=True, choices=[('P0', '冒烟用例'), ('P1', '系统的重要功能用例'), ('P2', '系统的一般功能用例'), ('P3', '极低级别的用例')], default='P1', max_length=10, null=True, verbose_name='用例优先级')),
                ('case_process_type', models.CharField(blank=True, choices=[('normal', '正常流'), ('unusual', '异常流')], default='normal', max_length=10, null=True, verbose_name='流程类型')),
                ('case_title', models.CharField(max_length=50, verbose_name='测试用例_名称')),
                ('case_precondition', models.TextField(blank=True, default='', null=True, verbose_name='测试用例_前置条件')),
                ('case_step', models.TextField(default='', verbose_name='测试用例_操作步骤')),
                ('case_expected_result', models.TextField(default='', verbose_name='测试用例_预期结果')),
                ('write_comments', models.TextField(blank=True, default='编写备注', null=True, verbose_name='编写备注')),
                ('write_case_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='编写用例时间')),
                ('ex_result', models.CharField(blank=True, choices=[('pass', '通过'), ('fail', '失败'), ('block', '锁定'), ('na', '未执行')], default='na', max_length=10, null=True, verbose_name='测试结果')),
                ('test_comments', models.TextField(blank=True, default='测试备注', null=True, verbose_name='测试备注')),
                ('rele_case', models.ManyToManyField(blank=True, default='', null=True, related_name='_testcase_rele_case_+', to='yinics.TestCase', verbose_name='关联的用例')),
                ('test_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='testuser', to=settings.AUTH_USER_MODEL, verbose_name='执行人员')),
                ('write_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='writeuser', to=settings.AUTH_USER_MODEL, verbose_name='编写人员')),
            ],
            options={
                'verbose_name': '编写测试用例',
                'verbose_name_plural': '编写测试用例',
            },
        ),
        migrations.CreateModel(
            name='CopyTestCase',
            fields=[
            ],
            options={
                'verbose_name': '执行测试用例',
                'verbose_name_plural': '执行测试用例',
                'proxy': True,
                'indexes': [],
            },
            bases=('yinics.testcase',),
        ),
        migrations.CreateModel(
            name='CopyTwoTestCase',
            fields=[
            ],
            options={
                'verbose_name': '查看测试用例',
                'verbose_name_plural': '查看测试用例',
                'proxy': True,
                'indexes': [],
            },
            bases=('yinics.testcase',),
        ),
    ]
