# Generated by Django 2.0.5 on 2019-02-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yinics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='write_comments',
            field=models.TextField(blank=True, default='备注', null=True, verbose_name='备注'),
        ),
    ]
