# Generated by Django 2.0.5 on 2019-04-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yinics', '0003_auto_20190222_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='answer_comments',
            field=models.TextField(blank=True, default='问题答复', null=True, verbose_name='问题答复'),
        ),
    ]
