# Generated by Django 2.0.5 on 2019-05-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yinics', '0005_auto_20190429_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='test_project',
            field=models.CharField(default='', help_text='测试项目', max_length=50, verbose_name='测试项目'),
        ),
    ]
