# Generated by Django 2.0.5 on 2019-07-17 10:22

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yinics', '0006_auto_20190507_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='write_comments',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='编写备注'),
        ),
    ]
