# Generated by Django 2.0.5 on 2019-07-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yinics', '0007_auto_20190717_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='write_comments',
            field=models.TextField(blank=True, default='编写备注', null=True, verbose_name='编写备注'),
        ),
    ]
