"""
Django settings for yiniceshi project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import sys   #导入sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0,os.path.join(BASE_DIR,'apps'))      #配置apps目录到根搜索目录
sys.path.insert(0,os.path.join(BASE_DIR,'extra_apps'))   #配置extra_apps目录到根搜索目录


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^81c6=g9h#nm%ljaall8-tr2icb3$iq9%z%87(bt2v0smiwm3='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['*']  #在这里请求的host添加了*可以使用域名访问


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'xadmin',  # 注册xadmin
    'crispy_forms',  # 注册xadmin的依赖应用crispy_forms
    'yinics',#注册yncs
    'pure_pagination',   #注册分页库
    'casereport.apps.CasereportConfig',   #注册casereport
    'checkcasecatelogue.apps.CheckcasecatelogueConfig',#注册checkcasecatelogue
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'yiniceshi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'yiniceshi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }
# DATABASES = {   #配置数据库为mysql
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': "yinishanghu",
#         'USER':"root",
#         'PASSWORD':"root",
#         'HOST':"localhost"
#     }
# }

# DATABASES = {   #配置数据库为mysql
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': "ct",
#         'USER':"root",
#         'PASSWORD':"root",
#         'HOST':"localhost"
#     }
# }

DATABASES = {   #配置数据库为mysql
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': "yntestcase",
        'USER':"root",
        'PASSWORD':"root",
        'HOST':"localhost"
    }
}

# DATABASES = {   #配置数据库为mysql
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': "casereport",
#         'USER':"root",
#         'PASSWORD':"root",
#         'HOST':"localhost"
#     }
# }

# DATABASES = {   #配置数据库为mysql
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': "yinni_testcase",
#         'USER':"root",
#         'PASSWORD':"root",
#         'HOST':"localhost"
#     }
# }
# DATABASES = {   #配置数据库为mysql
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': "testcase",
#         'USER':"test3306",
#         'PASSWORD':"test_iapp",
#         'HOST':"192.168.1.4",
#         'PORT': '3308'
#     }
# }



# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

# USE_TZ = True

LANGUAGE_CODE = 'zh-hans'   #语言改为中文

TIME_ZONE = 'Asia/Shanghai'   #时区设置为上海
USE_TZ = False   #时间为本地时间，即上海时间，如果为True，则时间取得的是UTC的时间，即国际时间


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]   #将static加入python跟搜索路径


#网站域名及端口配置
YMDK = 'http://ynqbsh.com:8000'
