# Generated by Django 2.0.5 on 2019-01-16 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_project', models.CharField(default='', max_length=50, verbose_name='测试项目')),
                ('test_module', models.CharField(default='', max_length=50, verbose_name='测试模块')),
                ('is_repeat', models.BooleanField(default=True, help_text='是否重复', verbose_name='是否重复')),
                ('add_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '测试用例统计报告',
                'verbose_name_plural': '测试用例统计报告',
            },
        ),
        migrations.CreateModel(
            name='CaseReportTwo',
            fields=[
            ],
            options={
                'verbose_name': '项目统计',
                'verbose_name_plural': '项目统计',
                'proxy': True,
                'indexes': [],
            },
            bases=('casereport.casereport',),
        ),
    ]
