# Generated by Django 2.0.5 on 2019-02-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casereport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casereport',
            name='is_repeat',
            field=models.BooleanField(default=True, help_text='是否重复项目', verbose_name='是否重复项目'),
        ),
    ]
